apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: bob-csr
spec:
  groups:
  - system:autenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1pUQ0NBVTBDQVFBd0lERU1NQW9HQTFVRUF3d0RZbTlpTVJBd0RnWURWUVFLREFkc1pXRnlibVZ5TUlJQgpJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNEVGM3pPSjFGYjhXTURaSWhyTWZKR1pICmZkc01aTFZLUmVkTk0yVWdMWkxzMXlpcFhQQittL1VlMWd6RVVpb0R6Q0NFUXBVTG41ajkrRnFPUlhETEtDMG4KWFFLQUNZUmRxVEhpcFRXcnU2bnI5V0JCWjFtM2RobDdVSUVtTVBhbnNTZGU1R0RZRGZnWlh2NndJNEVJVlB4KwpZdkxwM3hVeFJFUnM3VkpCeUQwcjhpNmE2SldKSFh0c2YyOVhneGFQazY3QW11Z1BJcWl3VThxaDhrRnN2d1AxCk1veVA4Y2hsa0RmTU5PUVV5R2dIMXkyelRhT3RXcVZEK1NmZ0YzS3BGVFFLNU92L1VhVXNVSEE4dVBUejZmTlcKT1hSWG5KcVB0V2tCYWJlNmZ6ckMyMmE1RmUxY1ZMalczNGpwc05vb2tYNlorQ2VEbjJhOFBjdTBYNjdMWndJRApBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJVTFkck5kMStzMi96TkZ6eHNGTjJDb2UrSVVhNVdjCjVqUE5rczkzUlpUMmRPbkdZanFKcGlZR0ZTN0VQSEJrN0pIeU9TeUlxSnI0VWhFdWhuYVV6ZmUzU0hNbDJlNFAKZE55K3NCK0Z1V3QwTGRxdUlCdXBkeFY3b2huTmhjTXcrbEhKOGtGKzloNTRhOTBONDlvWlFNQkRDTDdqVmZIeQpxNEEvbUFtOFVuQVd2YnJ3ZVhZZVU2Z01wT1N6S0U1OGo1UGhqS2E2QWtjcjFnRDhuWDRpd3doOHpLQW4vM3htCm1zK3BZZjVpa0FZYjR3MTRjNEpTdWpzNGxRelV2UGdRUnM0Z2dvSzVvaUh4aHBhM2tWZCtFU3VlTFRqSjF4ZmoKMUNYMXNHWGFVODQwSjd6Z25BNy9rbHVIbnlHYlFMZW4vUDJsYmxpLytMT1NBT3hQWjlsWUU2Yz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg== 
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
